name: BATILI.Coach
favicon: null
layout_spectrum: 0.36657354631461203
typography_spectrum: 0.12475900421850383
title: Personal Coach for Ahead
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6e7a88'
    - '#1a2514'
    - '#a69d7e'
    - '#f9bf91'
  brandStrength: 0.4490014493931085
  lightness: 0.3216418828815222
  saturation: 0.2929959713947028
  rhythmicContrast: 0.5901653228793293
purpose: []
